---
# Version of Arduino IDE to install, will be interpolated in download URLs.
arduino_version: "1.8.10"

# URLs for fetching the source files from remote.
arduino_ide_url: "https://downloads.arduino.cc/arduino-{{ arduino_version }}-linux64.tar.xz"
arduino_ide_checksums_url: "https://downloads.arduino.cc/arduino-{{ arduino_version }}.sha512sum.txt"

# Location for saving and extracting Arduino archives.
arduino_download_directory: /opt/arduino

# Communications port for interfacing with the Arduino board. Toolkit defaults
# to serial port COM1, but USB is a saner default.
arduino_port: /dev/ttyUSB0

arduino_mk_deps:
  - python-serial
  - screen   # for making monitor
